version: '3'

services:
  db:
    image: oracle/database:21.3.0-ee
    container_name: db_proyecto_docente
    hostname: system
    domainname: evaluacion-docente.com
    environment:
      ORACLE_SID: DBDOC
      ORACLE_PDB: DBPDOC
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    ports:
      - "1521:1521"
      - "5500:5500"
    tty: true
    privileged: true
    networks:
      - proyecto-docente-network
    volumes:
      - oracle-data:/opt/oracle/oradata

  microservicio_curso_estudiante:
    image: microservicio-curso-estudiante:1.1
    container_name: microservicio_curso_estudiante
    ports:
      - "8080:8080"
    environment:
      ORACLE_SID: DBDOC # Container database name
      ORACLE_PDB: DBPDOC # Pluggable database name
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    depends_on:
      - db
    networks:
      - proyecto-docente-network

  autenticacion:
    image: microservicio-autenticacion:1.1
    container_name: microservicio_autenticacion
    ports:
      - "8081:8081"
    environment:
      ORACLE_SID: DBDOC # Container database name
      ORACLE_PDB: DBPDOC # Pluggable database name
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    depends_on:
      - db
    networks:
      - proyecto-docente-network
  
  evaluacion:
    image: microservicio-evaluacion:1.1
    container_name: microservicio_evaluacion
    ports:
      - "8082:8082"
    environment:
      # Configuración del microservicio
      ORACLE_SID: DBDOC # Container database name
      ORACLE_PDB: DBPDOC # Pluggable database name
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    depends_on:
      - db
    networks:
      - proyecto-docente-network
      
  formulario:
    image: microservicio-formulario:1.1
    container_name: microservicio-formulario
    ports:
      - "8083:8083"
    environment:
      # Configuración del microservicio
      ORACLE_SID: DBDOC # Container database name
      ORACLE_PDB: DBPDOC # Pluggable database name
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    depends_on:
      - db
    networks:
      - proyecto-docente-network
  
  docente:
    image: microservicio-docente:1.1
    container_name: microservicio-docente
    ports:
      - "8084:8084"
    environment:
      # Configuración del microservicio
      ORACLE_SID: DBDOC # Container database name
      ORACLE_PDB: DBPDOC # Pluggable database name
      ORACLE_PWD: Espe.2023
      ORACLE_CHARACTERSET: AL32UTF8
      ORA_SDTZ: Ecuador
    depends_on:
      - db
    networks:
      - proyecto-docente-network

networks:
  proyecto-docente-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local
